name: clang-format check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Run clang-format style check
      uses: jidicula/clang-format-action@v4.4.1
      with:
        clang-format-version: '14'
        exclude-regex: 'extlib/'